version: "3"
services:
  sqldb:
    build:
      context: ./
      dockerfile: Dockerfile_sql
    volumes:
      - ./:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sampleDB
    ports:
      - 3307:3306
    expose:
      - 3307
    hostname: pbl_sqldb_1

  python: # service名
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /opt/app/pbl
    command: bash -c " git pull && python main.py"
    tty: true
    expose:
      - "5000"
      - "3000"
      - "80"

    ports:
      - "80:80"
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - sqldb
